server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active: "qa"

build:
  version: 1.0

loans:
  message: "Learning Advance SpringBoot will switch in next 3 months"
  contactDetails:
    name: "Rahul Kumar"
    email: "Yadhuwanshirahulraaz@gmail.com"
  onCallSupport:
    - (055)654343
    - (055)667754
