
build:
  version: "live"

accounts:
  message: "Message from live/prod profile"
  contactDetails:
    name: "live server"
    email: "live@server.com"
  onCallSupport:
    - (911)3456778
    - (911)2346789